### ISSUE TITLE
Android share link to Facebook profile crash app

### ISSUE THREAD

**Issue by kristijantomic** [thebergamo/react-native-fbsdk-next#212]
Hi all,

i am not sure if anyone else have following error. If you try to share a link to Facebook profile.

```text
Fatal Exception: java.lang.RuntimeException: Could not invoke FBShareDialog.canShow
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:383)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:237)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:919)

Caused by java.lang.reflect.InvocationTargetException
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:237)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:919)

Caused by java.lang.NoSuchMethodError: No virtual method setImageUrl(Landroid/net/Uri;)Lcom/facebook/share/d/g$a; in class Lcom/facebook/share/d/g$a; or its super classes (declaration of 'com.facebook.share.d.g$a' appears in base.apk)
       at com.facebook.reactnative.androidsdk.Utility.buildShareLinkContent(Utility.java:172)
       at com.facebook.reactnative.androidsdk.Utility.buildShareContent(Utility.java:129)
       at com.facebook.reactnative.androidsdk.FBShareDialogModule.canShow(FBShareDialogModule.java:73)
       at java.lang.reflect.Method.invoke(Method.java)
       at com.facebook.react.bridge.JavaMethodWrapper.invoke(JavaMethodWrapper.java:372)
       at com.facebook.react.bridge.JavaModuleWrapper.invoke(JavaModuleWrapper.java:188)
       at com.facebook.react.bridge.queue.NativeRunnable.run(NativeRunnable.java)
       at android.os.Handler.handleCallback(Handler.java:883)
       at android.os.Handler.dispatchMessage(Handler.java:100)
       at com.facebook.react.bridge.queue.MessageQueueThreadHandler.dispatchMessage(MessageQueueThreadHandler.java:27)
       at android.os.Looper.loop(Looper.java:237)
       at com.facebook.react.bridge.queue.MessageQueueThreadImpl$4.run(MessageQueueThreadImpl.java:226)
       at java.lang.Thread.run(Thread.java:919)
```

I added all what is listed on:
[Sharing on Android](https://developers.facebook.com/docs/sharing/android)
[Getting Started with the Facebook SDK for Android](https://developers.facebook.com/docs/android/getting-started/)

Tried to debug with Android studio and it seems as soon as it hits shareDialog.canShow method call, app crashes.
![Screenshot 2022-03-04 at 08 08 13](https://user-images.githubusercontent.com/1470994/156716169-5cc90d0a-6f28-478c-ab3d-458c66191dad.png)

Filepath: app/node_modules/react-native-fbsdk next/android/src/main/java/com/facebook/reactnative/androidsdk/FBShareDialogModule.java

App crashes both on virtual devices and on real devices. iOS share works fine.

## Environment
"react-native": "0.67.3",
"react-native-fbsdk-next": "^7.3.2",

**Comment by mikehardy** [comment]
:thinking: 

troubleshooting process:
- verify exactly what version of facebook-android-sdk you are getting in your build (`cd android && ./gradlew :app:dependencies > dependencies.txt`) then search through dependencies.txt to find the version that was ultimately resolved
- check facebook-android-sdk repo to see if the method called does in fact exist on the release you pull in (and if different from what we try to pull in, if it exists on the version we try to pull in https://github.com/thebergamo/react-native-fbsdk-next/blob/bdf91b6a9fed0154b489e06ffa09257637886e2a/android/build.gradle#L47)
- check facebook-android-sdk release notes to see if there has been some change recently in method availability or method signature that would result in this

At all steps, `npx react-native-clean-project` may be interesting to make sure the versions you determine are *actually* the versions that were built into the app as installed on device

These sorts of errors ("react-native module is trying to use some non-existent native module API") are almost always version mis-matches, so all troubleshooting is focused pretty tightly on that

**Comment by kristijantomic** [comment]
Hi @mikehardy, thank you for the details! 

I did as you pointed out. I am not Java developer, but this is what i have found:

In the dependencies.txt file it seems that sdk for share resolves:
com.facebook.android:facebook-share:latest.release -> 13.0.0

Facebook share [docs](https://developers.facebook.com/docs/sharing/android) have example of share with the new API as follow:
```java
ShareLinkContent content = new ShareLinkContent.Builder()
        .setContentUrl(Uri.parse("https://developers.facebook.com"))
        .build();
```

Also in facebook GitHub repo Facebook SDK sdk-version-13.0.0 in the [ShareApi.java](https://github.com/facebook/facebook-android-sdk/blob/main/facebook-share/src/main/java/com/facebook/share/ShareApi.java) on line 165 have chack if instanceof ShareLinkContent

I searched in the repo for [canShow](https://github.com/facebook/facebook-android-sdk/search?q=canShow) it pops up in multiple files, one of them is [ShareDialog.kt](https://github.com/facebook/facebook-android-sdk/blob/8ddcde1ed501b71dd45f6d46e34f403727dca760/facebook-common/src/main/java/com/facebook/share/widget/ShareDialog.kt).

Really not sure what should i do 😞

**Comment by mikehardy** [comment]
This is a problem:

> In the dependencies.txt file it seems that sdk for share resolves:
com.facebook.android:facebook-share:latest.release -> 13.0.0

It should be on v12, we specify v12+ in the build.gradle here specifically to constrain the major version.
We are not compatible with v13 yet and this is exactly the sort of error I would expect if you use this library (written against v12 currently) with the v13 SDK containing breaking changes

How is v13 coming in ? Very very strange. Our example does not show this behavior, it stays locked to v12:

```

.mike@osxvm:~/work/react-random/react-native-fbsdk-next/RNFBSDKExample/android (master) % ./gradlew :app:dependencies > dependencies.txt
mike@osxvm:~/work/react-random/react-native-fbsdk-next/RNFBSDKExample/android (master) % cat dependencies.txt |grep facebook-android
     \--- com.facebook.android:facebook-android-sdk:12.+ -> 12.3.0
     \--- com.facebook.android:facebook-android-sdk:12.+ -> 12.3.0
     \--- com.facebook.android:facebook-android-sdk:12.+ -> 12.3.0
     \--- com.facebook.android:facebook-android-sdk:12.+ -> 12.3.0
```

So something about your project is allowing v13 to come in, that needs examination and fixing in your project's build.gradle's somewhere I think?

**Comment by kristijantomic** [comment]
Yes, you ara totally right. I messed up SDK version.

I have changed SDK dependencies in android/app/build.gradle

I used to have this version:

```gradle
 implementation 'com.facebook.android:facebook-android-sdk:[5,6)'
```

but lately as I upgraded react-native-fbsdk-next and visited  [Getting Started Guide ](https://developers.facebook.com/docs/android/getting-started/)
to check if i miss something, and there iI found following listed:

```gradle 
implementation 'com.facebook.android:facebook-android-sdk:latest.release'
``` 
Reverted to the old one and share link works.

Thank you!

**Comment by mikehardy** [comment]
I checked our documentation here to see if we had led you astray (documentation bugs are subtle, usually evil) and I see this:

https://github.com/thebergamo/react-native-fbsdk-next#31-android

> You can skip the build.gradle changes since that's taken care of

So I think we're handling that as well as we can. You're not supposed to edit build.gradle if you are using this module

So I'll close this as resolved, but the other linked issue is still strange, I've got an open request for more information there and have not seen anything actionable yet:

> You may have more information in adb logcat (since this appears to be the android platform...)
