### ISSUE TITLE
yarn test fails on node > 16

### ISSUE THREAD

**Issue by ps-markevans** [thebergamo/react-native-fbsdk-next#438]
When using node >16 the tests fail due to an issue with Jest. 

```
$ node --version
v16.20.0
$ yarn test
yarn run v1.22.19
$ yarn validate:prettier && yarn validate:eslint && yarn jest
$ prettier "{src,jest,plugin/src}/**/*.{js,ts,tsx}" --check
Checking formatting...
All matched files use Prettier code style!
$ eslint "src/**/*"
$ jest
 PASS  plugin/src/__tests__/withSKAdNetworkIdentifiers-test.ts
 PASS  plugin/src/__tests__/withUserTrackingPermission-test.ts
 PASS  plugin/src/__tests__/withFacebookIOS-test.ts
 PASS  plugin/src/__tests__/withFacebookAndroid-test.ts
 PASS  RNFBSDKExample/__tests__/App-test.js

Test Suites: 5 passed, 5 total
Tests:       19 passed, 19 total
Snapshots:   0 total
Time:        1.359 s
Ran all test suites.
✨  Done in 4.46s.
```

Switch node version

```
$ node --version
v20.4.0
$ yarn test
yarn run v1.22.19
$ yarn validate:prettier && yarn validate:eslint && yarn jest
$ prettier "{src,jest,plugin/src}/**/*.{js,ts,tsx}" --check
Checking formatting...
All matched files use Prettier code style!
$ eslint "src/**/*"
$ jest
 FAIL  plugin/src/__tests__/withFacebookAndroid-test.ts
  ● Test suite failed to run

    TypeError: Cannot assign to read only property 'performance' of object '[object global]'

      at Object.<anonymous> (node_modules/react-native/jest/setup.js:419:20)

 FAIL  plugin/src/__tests__/withUserTrackingPermission-test.ts
  ● Test suite failed to run

    TypeError: Cannot assign to read only property 'performance' of object '[object global]'

      at Object.<anonymous> (node_modules/react-native/jest/setup.js:419:20)

 FAIL  RNFBSDKExample/__tests__/App-test.js
  ● Test suite failed to run

    TypeError: Cannot assign to read only property 'performance' of object '[object global]'

      at Object.<anonymous> (node_modules/react-native/jest/setup.js:419:20)

 FAIL  plugin/src/__tests__/withFacebookIOS-test.ts
  ● Test suite failed to run

    TypeError: Cannot assign to read only property 'performance' of object '[object global]'

      at Object.<anonymous> (node_modules/react-native/jest/setup.js:419:20)

 FAIL  plugin/src/__tests__/withSKAdNetworkIdentifiers-test.ts
  ● Test suite failed to run

    TypeError: Cannot assign to read only property 'performance' of object '[object global]'

      at Object.<anonymous> (node_modules/react-native/jest/setup.js:419:20)

Test Suites: 5 failed, 5 total
Tests:       0 total
Snapshots:   0 total
Time:        0.312 s, estimated 2 s
Ran all test suites.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.```

Upgrading to a newer version (^29.6.0) and the tests all pass successfully
```

```
$ node --version
v20.4.0
$ yarn test
yarn run v1.22.19
$ yarn validate:prettier && yarn validate:eslint && yarn jest
$ prettier "{src,jest,plugin/src}/**/*.{js,ts,tsx}" --check
Checking formatting...
All matched files use Prettier code style!
$ eslint "src/**/*"
$ jest
 PASS  RNFBSDKExample/__tests__/App-test.js
 PASS  plugin/src/__tests__/withFacebookAndroid-test.ts
 PASS  plugin/src/__tests__/withFacebookIOS-test.ts
 PASS  plugin/src/__tests__/withUserTrackingPermission-test.ts
 PASS  plugin/src/__tests__/withSKAdNetworkIdentifiers-test.ts

Test Suites: 5 passed, 5 total
Tests:       19 passed, 19 total
Snapshots:   0 total
Time:        0.45 s, estimated 1 s
Ran all test suites.
✨  Done in 3.59s.
```

**Comment by mikehardy** [comment]
I'm not sure this is still happening. Is still happening for you?
I see `yarn test` (or `yarn jest`) failing locally but for a different reason:

```

 FAIL  RNFBSDKExample/__tests__/App.test.tsx
  ● Test suite failed to run

    Invariant Violation: __fbBatchedBridgeConfig is not set, cannot invoke native modules

      at invariant (RNFBSDKExample/node_modules/invariant/invariant.js:40:15)
      at Object.invariant (RNFBSDKExample/node_modules/react-native/Libraries/BatchedBridge/NativeModules.js:182:3)
      at Object.require (RNFBSDKExample/node_modules/react-native/Libraries/TurboModule/TurboModuleRegistry.js:15:23)
```
