### ISSUE TITLE
ANR: art::ConditionVariable::WaitHoldingLocks

### ISSUE THREAD

**Issue by quangtuan28200** [thebergamo/react-native-fbsdk-next#588]
## 🐛 Bug Report
I'm using react-native 0.75.4, react-native-fbsdk-next 13.0.0

It seems has an error when calling getCurrentProfile in FBProfileModule

![image](https://github.com/user-attachments/assets/78407e5e-4b76-43a5-82ab-a25fdb65005f)

```
java.lang.RuntimeException: Illegal callback invocation from native module. This callback type only permits a single invocation from native code. 
  at com.facebook.react.bridge.CallbackImpl.invoke(CallbackImpl.java:26)
  at com.facebook.reactnative.androidsdk.FBProfileModule$2.onCurrentProfileChanged(FBProfileModule.java:60)
  at com.facebook.ProfileTracker$ProfileBroadcastReceiver.onReceive(ProfileTracker.kt:65)
  at androidx.localbroadcastmanager.content.LocalBroadcastManager.executePendingBroadcasts(LocalBroadcastManager.java:313)
  at androidx.localbroadcastmanager.content.LocalBroadcastManager$1.handleMessage(LocalBroadcastManager.java:121)
  at android.os.Handler.dispatchMessage(Handler.java:106) at android.os.Looper.loopOnce(Looper.java:230)
  at android.os.Looper.loop(Looper.java:319) at android.app.ActivityThread.main(ActivityThread.java:8900)
  at java.lang.reflect.Method.invoke(Native Method)
  at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:608)
  at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1103)
```

## To Reproduce
can not reproduce

## Environment
```
System:
  OS: macOS 13.6.6
  CPU: (8) x64 Intel(R) Core(TM) i7-7700 CPU @ 3.60GHz
  Memory: 2.10 GB / 32.00 GB
  Shell:
    version: "5.9"
    path: /bin/zsh
Binaries:
  Node:
    version: 20.10.0
    path: ~/.nvm/versions/node/v20.10.0/bin/node
  Yarn:
    version: 3.6.4
    path: ~/.nvm/versions/node/v20.10.0/bin/yarn
  npm:
    version: 10.2.3
    path: ~/.nvm/versions/node/v20.10.0/bin/npm
  Watchman:
    version: 2024.08.26.00
    path: /usr/local/bin/watchman
Managers:
  CocoaPods:
    version: 1.15.2
    path: /Users/ventura/.rubies/ruby-3.3.4/bin/pod
SDKs:
  iOS SDK:
    Platforms:
      - DriverKit 23.2
      - iOS 17.2
      - macOS 14.2
      - tvOS 17.2
      - visionOS 1.0
      - watchOS 10.2
  Android SDK:
    API Levels:
      - "28"
      - "30"
      - "31"
      - "32"
      - "33"
      - "34"
    Build Tools:
      - 29.0.2
      - 30.0.2
      - 30.0.3
      - 31.0.0
      - 32.0.0
      - 33.0.0
      - 33.0.1
      - 33.0.2
      - 34.0.0
      - 35.0.0
    System Images:
      - android-31 | Intel x86_64 Atom
      - android-33 | Google APIs Intel x86_64 Atom
      - android-34 | Intel x86_64 Atom
    Android NDK: Not Found
IDEs:
  Android Studio: 2024.2 AI-242.23339.11.2421.12700392
  Xcode:
    version: 15.2/15C500b
    path: /usr/bin/xcodebuild
Languages:
  Java:
    version: 17.0.11
    path: /usr/bin/javac
  Ruby:
    version: 3.3.4
    path: /Users/ventura/.rubies/ruby-3.3.4/bin/ruby
npmPackages:
  "@react-native-community/cli": Not Found
  react:
    installed: 18.3.1
    wanted: 18.3.1
  react-native:
    installed: 0.75.4
    wanted: 0.75.4
  react-native-macos: Not Found
npmGlobalPackages:
  "*react-native*": Not Found
Android:
  hermesEnabled: true
  newArchEnabled: false
iOS:
  hermesEnabled: true
  newArchEnabled: false
  ```

**Comment by mikehardy** [comment]
Based on the stack trace I'm not sure how I would reproduce that either. I can't see how a race condition could get in there and result in the callback being invoked multiple times

If you can figure it out and propose a PR I'd welcome it

https://github.com/thebergamo/react-native-fbsdk-next/blob/09233b8f8905babc87608d8ed3dbbc248a680141/android/src/main/java/com/facebook/reactnative/androidsdk/FBProfileModule.java#L40-L67
